# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  paths:
    include:
    - ./pom.xml
  tags:
    include:
      - base/*
  branches:
    include:
      - master
      - development

# By default, use self-hosted agents
pool:
  vmImage: ubuntu-latest

# Opting out of pull request validation
pr: none

resources:
  repositories:
    # Azure DevOps repository
    - repository: talpa-verkkokauppa-pipelines
      type: git
      # project/repository
      name: talpa-verkkokauppa/talpa-verkkokauppa-pipelines

extends:
  template: azure-pipelines-talpa-verkkokauppa-base.yml@talpa-verkkokauppa-pipelines